# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-21 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thyme', '0002_snapshot_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='agent',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
