# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 10:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thyme', '0003_snapshot_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=128)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='snapshot',
            name='data',
        ),
        migrations.AddField(
            model_name='snapshot',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='raw',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snapshot',
            name='slug',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='blacklist',
            unique_together=set([('owner', 'slug')]),
        ),
    ]
